version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: Install Newman HTML reporter
          command: 'sudo npm install -g newman-reporter-html'
      
      - run:
          name: Install Newman Package
          command: 'sudo npm install -g newman'
  
      - run:
          name: Create Report Directory
          command: 'mkdir ~/repo/junit'
    
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Run Stage Targetable API tests
          command: 'newman run https://api.getpostman.com/collections/6778f995-2941-4e95-8576-c45cd4ce532e?apikey=9c67cdddfbc64bc48cbfdd26b8ddc469 --environment stage.json --reporters html --reporter-cli-no-summary --reporter-html-export ~/repo/junit/export_text.html --bail'
    
      # Store test results
      - store_test_results:
          path: ~/repo/junit/
 

 
