version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/6778f995-2941-4e95-8576-c45cd4ce532e?apikey=9c67cdddfbc64bc48cbfdd26b8ddc469
          environment: ./stage.json
          timeout: '1000'
